language: generic 

sudo: required

services: 
  - docker

before_install: 
  - docker build -t raminblair/udemy-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true raminblair/udemy-docker npm run test